import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header, { NavPage } from './header'
import Footer from './footer'
import ImageBackground from '@/components/ImageBackground'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, menu
}: {
  children: React.ReactNode, menu: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ''}>
        <ImageBackground imageUrl='/mainbg.png' className='h-screen bg-fixed w-screen overflow-hidden' imageClassName='bg-fixed blur-sm scale-110'>
          {menu}
          <Header navPage={<NavPage/>}/>
          {children}
          <Footer />
        </ImageBackground>
      </body>
    </html>
  )
}
