import type { Metadata } from 'next'
import '../../globals.css'
import Header from '../../header'
import Footer from '../../footer'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={'min-h-screen bg-navy-blue'}>
                <Header state={'menu'} />
                {children}
                <Footer />
            </body>
        </html>
    )
}