import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '../header'
import Footer from '../footer'
import ImageBackground from '@/components/ImageBackground'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' h-screen'}>
        <ImageBackground imageUrl='/mainbg.png' className='overflow-hidden' imageClassName='blur-sm scale-110' objectFit=''>
          <Header state={'default'} />
            {children}
          <Footer />
        </ImageBackground>
      </body>
    </html>
  )
}
